package image

// systemdAnalyzeVectors holds "systemd-analyze image-policy" output of systemd 262:
// per designator the MODE, READ-ONLY, GROWFS and FSTYPE columns.
var systemdAnalyzeVectors = []struct {
	policy string
	rows   map[string]string
}{
	{"*", map[string]string{
		"root":            "open - - -",
		"usr":             "open - - -",
		"home":            "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"srv":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"esp":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"xbootldr":        "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"swap":            "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"root-verity":     "unprotected+unused+absent - - -",
		"usr-verity":      "unprotected+unused+absent - - -",
		"root-verity-sig": "unprotected+unused+absent - - -",
		"usr-verity-sig":  "unprotected+unused+absent - - -",
		"tmp":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"var":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
	}},
	{"-", map[string]string{
		"root":            "ignore - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"~", map[string]string{
		"root":            "absent - - -",
		"usr":             "absent - - -",
		"home":            "absent - - -",
		"srv":             "absent - - -",
		"esp":             "absent - - -",
		"xbootldr":        "absent - - -",
		"swap":            "absent - - -",
		"root-verity":     "absent - - -",
		"usr-verity":      "absent - - -",
		"root-verity-sig": "absent - - -",
		"usr-verity-sig":  "absent - - -",
		"tmp":             "absent - - -",
		"var":             "absent - - -",
	}},
	{"=verity", map[string]string{
		"root":            "verity - - -",
		"usr":             "verity - - -",
		"home":            "- - - -",
		"srv":             "- - - -",
		"esp":             "- - - -",
		"xbootldr":        "- - - -",
		"swap":            "- - - -",
		"root-verity":     "- - - -",
		"usr-verity":      "- - - -",
		"root-verity-sig": "- - - -",
		"usr-verity-sig":  "- - - -",
		"tmp":             "- - - -",
		"var":             "- - - -",
	}},
	{"root=verity", map[string]string{
		"root":            "verity - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=signed", map[string]string{
		"root":            "signed - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=verity+signed:usr=unprotected+absent", map[string]string{
		"root":            "verity+signed - - -",
		"usr":             "unprotected+absent - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=verity+read-only-on:usr=signed+growfs-off+erofs", map[string]string{
		"root":            "verity yes - -",
		"usr":             "signed - no erofs",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected yes - -",
		"usr-verity":      "unprotected - no -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "unprotected - no -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=unprotected:=absent", map[string]string{
		"root":            "unprotected - - -",
		"usr":             "absent - - -",
		"home":            "absent - - -",
		"srv":             "absent - - -",
		"esp":             "absent - - -",
		"xbootldr":        "absent - - -",
		"swap":            "absent - - -",
		"root-verity":     "absent - - -",
		"usr-verity":      "absent - - -",
		"root-verity-sig": "absent - - -",
		"usr-verity-sig":  "absent - - -",
		"tmp":             "absent - - -",
		"var":             "absent - - -",
	}},
	{"root=verity+signed:root-verity=absent", map[string]string{
		"root":            "verity+signed - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "absent - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=ext4+squashfs", map[string]string{
		"root":            "open - - ext4+squashfs",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected+unused+absent - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected+unused+absent - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"=open", map[string]string{
		"root":            "open - - -",
		"usr":             "open - - -",
		"home":            "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"srv":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"esp":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"xbootldr":        "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"swap":            "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"root-verity":     "unprotected+unused+absent - - -",
		"usr-verity":      "unprotected+unused+absent - - -",
		"root-verity-sig": "unprotected+unused+absent - - -",
		"usr-verity-sig":  "unprotected+unused+absent - - -",
		"tmp":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
		"var":             "encrypted+encryptedwithintegrity+unprotected+unused+absent - - -",
	}},
	{"root=ignore:usr=open", map[string]string{
		"root":            "ignore - - -",
		"usr":             "open - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "unprotected+unused+absent - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "unprotected+unused+absent - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"usr=verity+read-only-on:root=encrypted:swap=encrypted", map[string]string{
		"root":            "encrypted - - -",
		"usr":             "verity yes - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "encrypted - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "unprotected yes - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=encrypted+read-only-off:srv=encrypted+absent:swap=absent", map[string]string{
		"root":            "encrypted no - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "encrypted+absent - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "absent - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=unprotected+encrypted:swap=absent+unused:=unprotected+encrypted+absent", map[string]string{
		"root":            "encrypted+unprotected - - -",
		"usr":             "encrypted+unprotected+absent - - -",
		"home":            "encrypted+unprotected+absent - - -",
		"srv":             "encrypted+unprotected+absent - - -",
		"esp":             "encrypted+unprotected+absent - - -",
		"xbootldr":        "encrypted+unprotected+absent - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected+absent - - -",
		"usr-verity":      "unprotected+absent - - -",
		"root-verity-sig": "unprotected+absent - - -",
		"usr-verity-sig":  "unprotected+absent - - -",
		"tmp":             "encrypted+unprotected+absent - - -",
		"var":             "encrypted+unprotected+absent - - -",
	}},
	{"root=erofs+squashfs:swap=absent+unused:=unprotected+encrypted+absent", map[string]string{
		"root":            "open - - erofs+squashfs",
		"usr":             "encrypted+unprotected+absent - - -",
		"home":            "encrypted+unprotected+absent - - -",
		"srv":             "encrypted+unprotected+absent - - -",
		"esp":             "encrypted+unprotected+absent - - -",
		"xbootldr":        "encrypted+unprotected+absent - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected+unused+absent - - -",
		"usr-verity":      "unprotected+absent - - -",
		"root-verity-sig": "unprotected+unused+absent - - -",
		"usr-verity-sig":  "unprotected+absent - - -",
		"tmp":             "encrypted+unprotected+absent - - -",
		"var":             "encrypted+unprotected+absent - - -",
	}},
	{"root=read-only-on+read-only-off+growfs-on", map[string]string{
		"root":            "open - yes -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected+unused+absent - yes -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected+unused+absent - yes -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"=signed+absent:usr-verity=open", map[string]string{
		"root":            "signed+absent - - -",
		"usr":             "signed+absent - - -",
		"home":            "absent - - -",
		"srv":             "absent - - -",
		"esp":             "absent - - -",
		"xbootldr":        "absent - - -",
		"swap":            "absent - - -",
		"root-verity":     "absent - - -",
		"usr-verity":      "unprotected+unused+absent - - -",
		"root-verity-sig": "absent - - -",
		"usr-verity-sig":  "absent - - -",
		"tmp":             "absent - - -",
		"var":             "absent - - -",
	}},
	{"root=unused+absent+growfs-on", map[string]string{
		"root":            "ignore - yes -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=absent+read-only-on", map[string]string{
		"root":            "absent - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "ignore - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "ignore - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=-", map[string]string{
		"root":            "open - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected+unused+absent - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unprotected+unused+absent - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"root=verity:root-verity-sig=unused", map[string]string{
		"root":            "verity - - -",
		"usr":             "ignore - - -",
		"home":            "ignore - - -",
		"srv":             "ignore - - -",
		"esp":             "ignore - - -",
		"xbootldr":        "ignore - - -",
		"swap":            "ignore - - -",
		"root-verity":     "unprotected - - -",
		"usr-verity":      "ignore - - -",
		"root-verity-sig": "unused - - -",
		"usr-verity-sig":  "ignore - - -",
		"tmp":             "ignore - - -",
		"var":             "ignore - - -",
	}},
	{"=verity+encrypted", map[string]string{
		"root":            "verity+encrypted - - -",
		"usr":             "verity+encrypted - - -",
		"home":            "encrypted - - -",
		"srv":             "encrypted - - -",
		"esp":             "encrypted - - -",
		"xbootldr":        "encrypted - - -",
		"swap":            "encrypted - - -",
		"root-verity":     "- - - -",
		"usr-verity":      "- - - -",
		"root-verity-sig": "- - - -",
		"usr-verity-sig":  "- - - -",
		"tmp":             "encrypted - - -",
		"var":             "encrypted - - -",
	}},
}
